version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: fastapi_backend
    ports:
      - "${APP_PORT}:8000"
    command: "uvicorn --factory application.main:create_app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./src/:/app
    env_file:
      - .env
    networks:
      - backend


networks:
  backend:
    driver: bridge